name: competencia_lazadores
description: Aplicación multiplataforma para competencias de lazadores de becerros.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.0.0

  # Persistencia con Drift (SQLite puro)
  drift: ^2.0.0
  path_provider: ^2.0.0

  # Import/Export Excel
  file_selector: ^1.0.3
  file_selector_macos: ^0.9.4+2
  excel: ^2.0.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Para generar código Drift
  drift_dev: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
